sellers yml and reviews yml
samdoghor/GomerceBE pull request #108
Opened 2023-06-14 23:19 UTC by TangoIndiaMango

Hi, i have sellers delete.yml and all the required yml files for the reviews ready for review.

2023-06-15 16:26 UTC, samdoghor commented
some files for the review are still missing, (read_all.yml and read_one.yml). Also, complete the sellers docs so review can be once.

Thank you.

2023-06-15 16:37 UTC, samdoghor commented
You didn't uncomment the swag decorator in the resource files.

2023-06-15 20:59 UTC, TangoIndiaMango commented
hi please i made a new push, do review. Thank you

2023-06-16 07:20 UTC, samdoghor requested changes

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/review/delete.yml
> +  - Reiview
Reviews

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/review/get_all.yml
> +  - Review
Reviews

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/review/post.yml
> +  - Review
Reviews

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/review/put.yml
> +    description: The product was Updated successfully
The review not product

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                last_name:
Indent to be on the same line with first_name

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                email:
Indent to be on the same line with first_name

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                phone:
Indent to be on the same line with first_name

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                username:
Indent to be on the same line with first_name

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                rating:
Indent to be on the same line with first_name

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/get_all.yml
> +                    "last_name": "Roe", "first_name": "Jerry",
To maintain same format across all docs bring first name down

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/post.yml
> +    description: The product was created successfully
Seller not product

2023-06-16 07:20 UTC, samdoghor commented on src/swagger/seller/put.yml
Email was not included as seen in others

2023-06-16 07:39 UTC, TangoIndiaMango commented on src/swagger/seller/put.yml
![image](https://github.com/samdoghor/GomerceBE/assets/89034378/a5b8f1b0-8339-40a3-bc33-4034d749dd3c)



It's not needed in the update method

2023-06-16 07:46 UTC, samdoghor approved these changes

2023-06-16 07:46 UTC, merged