feat: create shipping address model
samdoghor/GomerceBE pull request #41
Opened 2022-09-20 12:36 UTC by tee-code

Kindly review the PR.

2022-09-20 12:42 UTC, tee-code commented
I followed the data types used on Customer model created by Mary which is slightly different from the diagram. Let me know if am to switch back to the diagram. 

Note that the customer and order relationships would be created on their models as well. 

Thanks.

2022-09-20 15:45 UTC, samdoghor commented
Did you test run to ensure the database is working fine? If you did, you didn't commit your migration file.

2022-09-20 15:46 UTC, samdoghor requested changes
Tables names are now agreed to be in snake-case and not camel-case.

2022-09-20 16:25 UTC, tee-code commented
I do not want create migration file when the model is not approved. Just go through it for other corrections apart from table name and I will fix all at once. Thanks

2022-09-20 16:52 UTC, samdoghor commented
Everything seems ok, except the phone number and zipcode, any specific reason why you are using string as data type.

2022-09-21 12:47 UTC, samdoghor requested changes

2022-09-21 12:47 UTC, samdoghor commented on src/models/shipping_address.py
> +    __tablename__ = "shippingAddresses"
Table name should be in snake case

2022-09-21 12:47 UTC, samdoghor commented on src/models/shipping_address.py
> +    zipcode = db.Column(db.String(50))
This is ok, do not change the data type.

2022-09-21 12:47 UTC, samdoghor commented on src/models/shipping_address.py
> +    phone = db.Column(db.String(15), nullable=False)
This is ok, do not change the data type.

2022-09-21 12:54 UTC, closed without merging